import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { Header } from "@/components/layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  { label: "HOME", href: "/" },
  { label: "BAGS", href: "/bags" },
  { label: "SNEAKERS", href: "/sneakers" },
  { label: "BELT", href: "/belt" },
  { label: "CONTACT", href: "/contact" },
];

const categoryData: Record<string, string[]> = {
  BAGS: ["Handbags", "Backpacks", "Tote Bags"],
  SNEAKERS: ["Running Shoes", "Casual Sneakers", "High Tops"],
  BELT: ["Leather Belts", "Fabric Belts", "Designer Belts"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header
          navItems={navItems}
          cartItemCount={2}
          cartTotal="$0.00"
          categoryData={categoryData}
        />
        {children}
      </body>
    </html>
  );
}
