import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { Header } from "@/components/layout";
import { Footer } from "@/components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  { label: "HOME", href: "/" },
  { label: "BAGS", href: "/category/bags" },
  { label: "SNEAKERS", href: "/category/sneakers" },
  { label: "BELT", href: "/category/belt" },
  { label: "CONTACT", href: "/category/contact" },
];

const categoryData: Record<string, string[]> = {
  BAGS: ["Handbags", "Backpacks", "Tote Bags"],
  SNEAKERS: ["Running Shoes", "Casual Sneakers", "High Tops"],
  BELT: ["Leather Belts", "Fabric Belts", "Designer Belts"],
};

const footerData = {
  brand: {
    logoSrc: "/logo.svg",
    name: "E-Comm",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  socialLinks: {
    facebook: "https://facebook.com/ecomm",
    twitter: "https://twitter.com/ecomm",
  },
  contact: {
    address: "E-Comm, 4578 Marmora Road, Glasgow D04 89GR",
  },
  footerLinks: [
    { title: "Information", links: ["About Us", "Privacy Policy", "Terms & Conditions"] },
    { title: "Service", links: ["Customer Support", "Returns", "FAQ"] },
    { title: "My Account", links: ["Login", "Register", "Order History"] },
    { title: "Our Offers", links: ["Discounts", "Gift Cards", "Coupons"] },
  ],
  paymentMethods: [
    { src: "/assets/paypal.png", alt: "PayPal" },
    { src: "/assets/visa.png", alt: "Visa" },
    { src: "/assets/master-card.png", alt: "MasterCard" },
    { src: "/assets/western-union.png", alt: "Western Union" },
  ],
  copyrightText: "© 2024 E-Comm. All rights reserved.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header
          navItems={navItems}
          cartItemCount={2}
          cartTotal="$0.00"
          categoryData={categoryData}
        />
        {children}

        {/* Footer */}
        <Footer {...footerData} />
      </body>
    </html>
  );
}
